<?= $this->doctype(), "\n" ?>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8"/>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

        <meta http-equiv="Content-Language" content="en"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

        <title>REST Console</title>

        <meta name="robots" content="index,follow"/>
        <meta name="author" content="">
        <meta name="description" content="REST Console"/>
        <meta name="viewport" content="width=device-width,initial-scale=1">

        <script src="/js/modernizr-2.0.6.js"></script>

        <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,500,700' rel='stylesheet' type='text/css'/>

        <link href="/css/default.less" rel="stylesheet/less"/>

        <script src="/js/less-1.1.5.js"></script>
        <script src="/js/mootools-core-1.4.1.js"></script>
        <script src="/js/mootools-more-1.4.0.1.js"></script>
        <script src="/js/google-code-prettify/prettify.js"></script>
    </head>

    <body>
        <header class="navbar navbar-fixed">
            <div class="navbar-inner">
                <div class="container">
                    <div class="brand">
                        <img src="images/logo.png" align="left">REST Console<small>Homepage</small>
                    </div>

                    <ul class="nav">
                        <li class="active"><a href="/home">Home</a></li>
                        <li><a href="/sandbox">Sandbox</a></li>
                    </ul>
                </div>
            </div>
        </header>

        <div class="container">
            <?= $this->layout()->content ?>
        </div>

        <? if (APPLICATION_ENV == 'production'): ?>
            <script type="text/javascript">
                var _gaq = _gaq || [];
                _gaq.push(['_setAccount', 'UA-598217-26']);
                _gaq.push(['_setDomainName', 'restconsole.com']);
                _gaq.push(['_trackPageview']);

                (function() {
                    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                })();
            </script>
        <? endif ?>

        <!--[if lt IE 7 ]>
            <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
            <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
        <![endif]-->
    </body>
</html>
