<?= $this->doctype(), "\n" ?>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8"/>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

        <meta http-equiv="Content-Language" content="en"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

        <title>REST Console Sandbox</title>

        <meta name="robots" content="index,follow"/>
        <meta name="description" content="REST Console Sandbox"/>

        <meta name="viewport" content="width=device-width,initial-scale=1">

        <script src="/js/modernizr-2.0.6.js"></script>

        <link rel="stylesheet" type="text/css" href="/css/prettify.css"/>
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic|Orbitron:400,500,700,900|Droid+Sans+Mono"/>

        <link rel="stylesheet/less" href="/css/style.less"/>

        <script type="text/javascript" src="/js/less-1.2.1.js"></script>
        <script type="text/javascript" src="/js/prettify/prettify.js"></script>

        <script type="text/javascript" src="/js/mootools-core-1.4.2.js"></script>
        <script type="text/javascript" src="/js/mootools-more-1.4.0.1.js"></script>

        <script type="text/javascript" src="/js/analytics.js"></script>

        <script type="text/javascript" src="http://platform.twitter.com/widgets.js" async="true"></script>
        <script type="text/javascript" src="http://platform.linkedin.com/in.js" async="true"></script>
    </head>

    <body onload="prettyPrint()">
        <header class="navbar navbar-fixed">
            <div class="navbar-inner">
                <div class="container">
                    <div class="brand">
                        <img src="/images/logo/32.png" align="left">
                        <span>REST Console</span>
                        <small>Sandbox</small>
                    </div>

                    <ul class="nav">
                        <li class="active"><a href="/home"><i class="home"></i> <span>H</span>ome</a></li>
                        <li><a href="/sandbox"><i class="settings"></i> <span>S</span>andbox</a></li>
                    </ul>

                    <ul class="social pull-right">
                        <li>
                            <a tabindex="-1" href="https://twitter.com/share" class="twitter-share-button" data-url="http://sandbox.restconsole.com" data-text="Checkout @RESTConsole Sandbox" data-via="CodeInChaos" data-related="CodeInChaos,AhmadNassri" data-hashtags="HTTP,RESTful,Sandbox">Tweet</a>
                        </li>

                        <li>
                            <iframe allowtransparency="true" frameborder="0" scrolling="no" sandbox="allow-same-origin allow-top-navigation allow-forms allow-scripts" src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fsandbox.restconsole.com&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;height=21&amp;appId=199139246805784" tabindex="-1"></iframe>
                        </li>

                        <li>
                            <script type="IN/Share" data-url="http://sandbox.restconsole.com" data-counter="right"></script>
                        </li>
                    </div>
                </div>
            </div>
        </header>

        <div class="container">
            <?= $this->layout()->content ?>
        </div>

        <? if (APPLICATION_ENV == 'production'): ?>
            <script type="text/javascript">
                var _gaq = _gaq || [];
                _gaq.push(['_setAccount', 'UA-598217-26']);
                _gaq.push(['_setDomainName', 'restconsole.com']);
                _gaq.push(['_trackPageview']);

                (function() {
                    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                })();
            </script>
        <? endif ?>

        <!--[if lt IE 7 ]>
            <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
            <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
        <![endif]-->
    </body>
</html>
